services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=MediInsight'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=12345678'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    environment:
      - 'REDIS_PASSWORD=12345678'
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_USER=admin'
      - 'RABBITMQ_DEFAULT_PASS=admin'
    ports:
      - '5672:5672'
      - '15672:15672'