server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://113.45.193.21:3306/MediInsight
    username: root
    password: PSfQEwrRRIL6KQEhpZ4n5q71Y4QFeorqYP2JAv26VxE
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7
  mail:
    host: smtp.163.com
    username: linxy20040304@163.com
    password: PXILBFPDDKSNRFAI
  rabbitmq:
    addresses: 113.45.193.21
    username: root
    password: PSfQEwrRRIL6KQEhpZ4n5q71Y4QFeorqYP2JAv26VxE
    virtual-host: /
  data:
    redis:
      host: 113.45.193.21
      password: PSfQEwrRRIL6KQEhpZ4n5q71Y4QFeorqYP2JAv26VxE
      port: 6379

springdoc:
  swagger-ui:
    path: /doc/ui/
  api-docs:
    path: /doc/json

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl