server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MediInsight
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7

springdoc:
  swagger-ui:
    path: /doc/ui
  api-docs:
    path: /doc/json